mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:com/rg/ucenterservice/mapper/xml/*.xml
server:
    port: 8160
spring:
    application:
        name: service-ucenter
    cloud:
        nacos:
            discovery:
                server-addr: 192.168.174.128:8848
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 123456
        url: jdbc:mysql://192.168.174.128:3306/guli_edu
        username: root
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    redis:
        database: 0
        host: 192.168.174.128
        lettuce:
            pool:
                max-active: 20
                max-idle: 5
                max-wait: -1
                min-idle: 0
        port: 6379
        timeout: 1800000
wx:
    open:
        app_id: xxx
        app_secret: xxxxx
        redirect_url: http://localhost:8160/api/ucenter/wx/callback
