server:
    port: 8007
spring:
    application:
        # 服务名称
        name: service-order
    cloud:
        nacos:
            discovery:
                server-addr: 192.168.174.128:8848 # 注册地址
    # 数据源信息
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 123456
        url: jdbc:mysql://192.168.174.128:3306/guli_edu
        username: root
    jackson: #JSON日期格式
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
# MP相关配置
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:com/rg/orderservice/mapper/xml/*.xml #XML目录

# 熔断开关
feign:
    hystrix:
        enabled: true
# 超时时间
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 3000