mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:com/rg/aclservice/mapper/xml/*.xml # 扫描mapper接口
server:
    port: 8009
spring:
    application:
        name: service-acl
    cloud:
        nacos:
            discovery:
                server-addr: 192.168.174.128:8848 # nacos服务地址
    datasource: # 数据源配置
        driver-class-name: com.mysql.jdbc.Driver
        password: 123456
        url: jdbc:mysql://192.168.174.128:3306/guli_acl?serverTimezone=GMT%2B8
        username: root
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    redis: # redis配置
        database: 0
        host: 192.168.174.128
        lettuce:
            pool:
                max-active: 20
                max-idle: 5
                max-wait: -1
                min-idle: 0
        port: 6379
        timeout: 1800000
