server:
    port: 10001 # 端口号
spring:
    application:
        name: canal-client # 服务名
    # mysql数据库连接
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/guli_edu?serverTimezone=GMT%2B8
        username: root
